### ISSUE TITLE
Feature request: Open from rawgit

### ISSUE THREAD

**Issue by chinchang** [softvar/enhanced-github#11]
To render files with correct content-type header, github files can be opened from rawgit.com

**Comment by softvar** [comment]
Rawgit will soon be shutdown. Read [here](https://rawgit.com/)
I have used `https://raw.githubusercontent.com` for rendering and takes care of MIME types.

Also, clicking on download icon opens up raw link directly.
`Alt+Click` on Mac OSX will download a file.
