### ISSUE TITLE
when download a script, it always open a new tabs in chrome without downloading.

### ISSUE THREAD

**Issue by huguyuehuhu** [softvar/enhanced-github#24]
Hi, thank you for sharing this excellent repo.  1. When I use` Ctrl+click ` to download a python script, e.g [here](https://github.com/lennylxx/ipv6-hosts), it always opens a new tab in chrome without downloading; 2. Then I use `Ctrl + S`  to save the script, but it always changes the format of the file from 'XX.py' to 'XX.py.txt'. 3.  it seems is related to [this](https://github.com/softvar/enhanced-github/issues/4) and [this](https://github.com/softvar/enhanced-github/issues/12), but I haven't found out a solution. Can you give me some help? thank you very much!

**Comment by softvar** [comment]
Use `Alt+Click` on Mac OSX to directly download a file. It doesn't change the extension.
Please try on your end and let me know. Thanks!
