### ISSUE TITLE
No enhancement if navigating Forward / Back

### ISSUE THREAD

**Issue by Yzrsah** [softvar/enhanced-github#33]
While navigating around GitHub, I was confused when most of my GitHub tabs were not showing any enhanced info.

If you press Forward or Back, the GitHub page will not be enhanced. It only works if you explicitly press 'refresh' or load the page for the first time.

Unfortunately I had to disable the extension because it's too inconsistent. By my use patterns, I can't see the enhanced info most of the time.

It would be awesome if this could be fixed.

**Comment by softvar** [comment]
This was an issue long back. Now Enhanced GitHub strongly supports the Single-Page-Application behavior of GitHub webpage. Please update your extension to the latest version and enjoy the extension whenever you browse the GitHub.
