### ISSUE TITLE
It doesn't work on edge chromium

### ISSUE THREAD

**Issue by TheGreat2201** [softvar/enhanced-github#38]
Can you please make work on edge chromium? Thanks

**Comment by TheGreat2201** [comment]
Can you please make work on edge chromium? Thanks

**Comment by TheGreat2201** [comment]
Close this please, didn't know you needed an access token now

**Comment by softvar** [comment]
An access token is only required for Private repos or if you have succeeded the [API rate limiting](https://developer.github.com/v3/rate_limit/).
Thanks for letting me know. Closing this issue now.
