### ISSUE TITLE
Can't see copy file and download options

### ISSUE THREAD

**Issue by TheGreat2201** [softvar/enhanced-github#39]
I can't see copy file and download options while viewing a file, I can only see the download option while viewing a tree/folder

**Comment by TheGreat2201** [comment]
![image](https://user-images.githubusercontent.com/36493671/56517225-03fec100-655a-11e9-82e6-9440e06a1ad8.png)

**Comment by debugjoker** [comment]
Me too.

**Comment by softvar** [comment]
Thanks for reporting. Seems like Github has updated the class-names.

**Comment by softvar** [comment]
It's fixed in v2.0.3.

**Comment by Justsoos** [comment]
v2.1.0 chrome Version 78.0.3904.108, not work now, did Github change the class-name again recently?

**Comment by softvar** [comment]
@Justsoos  Have released a new patch `v2.1.1`. It will be published on Chrome Web store soon.
