### ISSUE TITLE
Feature Request: Firefox version

### ISSUE THREAD

**Issue by jubyshu** [softvar/enhanced-github#45]
I really like this extension but I switch to Firefox recently and can't use it anymore. I have tried to search an add-on or a script which has the similar function, and I also tried chrome store foxified but it didn't work. So it will be nice if you can release a Firefox version. Thanks.

**Comment by ent3r** [comment]
Is there a status on this? What would be required to make this work in firefox?

**Comment by PixsaOJ** [comment]
Yea, please make it available on Firefox too...

**Comment by Bamajon1974** [comment]
+3!

**Comment by tcelestino** [comment]
https://addons.mozilla.org/en-US/firefox/addon/enhanced-github/
