### ISSUE TITLE
Feature Request: FireFox Version 

### ISSUE THREAD

**Issue by Bamajon1974** [softvar/enhanced-github#51]
Feature Request: Can this extension be ported to FireFox? 

Thanks in advance!

**Comment by Bamajon1974** [comment]
Feature Request: Can this extension be ported to FireFox?

Thanks in advance!

**Comment by tcelestino** [comment]
https://addons.mozilla.org/en-US/firefox/addon/enhanced-github/

**Comment by Bamajon1974** [comment]
Thank you very much!
