### ISSUE TITLE
chrome 81, fail to open options

### ISSUE THREAD

**Issue by cc978** [softvar/enhanced-github#58]
chrome Version 83.0.4103.61
enhanced Version 3.1.0
can not open options and input token, is it because of the iframe?
![image](https://user-images.githubusercontent.com/63266600/82726425-9bfb4b00-9d16-11ea-925e-b3ed753b6b7c.png)

**Comment by softvar** [comment]
Update your browser, please. I checked in Chrome 83 and is working with v4.0.1 of extension.

Click on Extension Options:

<img width="687" alt="Screenshot 2020-07-23 18 26 12" src="https://user-images.githubusercontent.com/4180800/88288969-26116100-cd12-11ea-83dc-c9756ffc3dd8.png">


**How Options look like**

<img width="968" alt="Screenshot 2020-07-23 18 26 28" src="https://user-images.githubusercontent.com/4180800/88288981-2b6eab80-cd12-11ea-8638-d50b01c3c75b.png">
