### ISSUE TITLE
Feature Request: Support for Github new repository layout

### ISSUE THREAD

**Issue by alvin96** [softvar/enhanced-github#59]
Github released a new repository layout recently, but seems like it is still in beta cause not everyone get this

![Annotation 2020-06-03 145352](https://user-images.githubusercontent.com/20142859/83605325-4c384180-a5aa-11ea-9393-e4ca131dfe28.png)

This is a preview of new layout

![screenshot](https://user-images.githubusercontent.com/20142859/83605805-23fd1280-a5ab-11ea-80d2-e8c254b0b391.png)

**Comment by softvar** [comment]
Thanks for letting me know @alvin96 .

Changes live in v4.0.0. Please update your extension to support new GitHub Design - https://chrome.google.com/webstore/detail/enhanced-github/anlikcnbgdeidpacdbdljnabclhahhmd

**Comment by alvin96** [comment]
Thanks for your update, love it👍
