### ISSUE TITLE
why it not work at all

### ISSUE THREAD

**Issue by xgqfrms** [softvar/enhanced-github#61]
# why it not work at all

![image](https://user-images.githubusercontent.com/7291672/85276788-f40fa380-b4b4-11ea-8d63-df039f0ff184.png)

**Comment by softvar** [comment]
If it's a private repo, you may need to add the GitHub Access Token. Or, please check if Rate Limiting is causing this.

Please update to `v4.0.0` and let me know if you still face any issues - https://chrome.google.com/webstore/detail/enhanced-github/anlikcnbgdeidpacdbdljnabclhahhmd?hl=en

**Comment by xgqfrms** [comment]
# that's OK now, Thanks a lot!

![image](https://user-images.githubusercontent.com/7291672/85739898-c5533080-b733-11ea-9863-03f45633df24.png)


![image](https://user-images.githubusercontent.com/7291672/85740066-e582ef80-b733-11ea-8f86-f11e7d32c4d3.png)
