### ISSUE TITLE
[IMPORTANT!!!!!!] GitHub Layout Change

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [softvar/enhanced-github#62]
I love this tool! 

But.... 

This tool needs to be updated to reflect the new UI changes GitHub has implemented within the last day.

**Comment by softvar** [comment]
Thanks for letting me know @YogiOnBioinformatics ! 👍 
On it!

**Comment by YogiOnBioinformatics** [comment]
I love your tool and I hope it's not too hard to fix things. 

Do you have any idea how long it will take till there's a Chrome extension update for your tool?

**Comment by softvar** [comment]
Changes live in `v4.0.0`. Please update your extension - https://chrome.google.com/webstore/detail/enhanced-github/anlikcnbgdeidpacdbdljnabclhahhmd

**Comment by YogiOnBioinformatics** [comment]
Yayyy!!!! 😄 

that was quick! 
thanks again for the update and for this extension
