### ISSUE TITLE
Displays multiple repo size, sometimes.

### ISSUE THREAD

**Issue by Miao-Mico** [softvar/enhanced-github#66]
![image](https://user-images.githubusercontent.com/42897857/87238606-36366000-c437-11ea-9e28-6f7dcbda2b39.png)

**Comment by softvar** [comment]
Please share the steps to reproduce.

**Comment by Miao-Mico** [comment]
> Please share the steps to reproduce.

Yes, I try to find a way to reproduce, here it is.

![enhanced-github-feedback](https://user-images.githubusercontent.com/42897857/87284861-6eb66680-c529-11ea-94d8-89d2b7402ca8.gif)

**Comment by Miao-Mico** [comment]
And, Would you consider to release a MS Edge version?

**Comment by ahmadawais** [comment]
Same issue. macOS Chrome.

![image](https://user-images.githubusercontent.com/960133/87685067-66b22d00-c79c-11ea-925c-bf0afec8c4d6.png)

**Comment by softvar** [comment]
@Miao-Mico @ahmadawais Thanks for reporting this. I have sent a fix for the same.
Please update the extension(***v4.0.1***) and the issue should not come.

**Comment by softvar** [comment]
@Miao-Mico Good News! I'm working on rolling this for Microsoft Edge browser. Stay tuned! :)

**Comment by Miao-Mico** [comment]
> @Miao-Mico Good News! I'm working on rolling this for Microsoft Edge browser. Stay tuned! :)

Thanks.
OH, Yes, I would.

**Comment by softvar** [comment]
@Miao-Mico The extension is now available on Microsoft Edge also.
Please check out: https://microsoftedge.microsoft.com/addons/detail/enhanced-github/eibibhailjcnbpjmemmcaakcookdleon

**Comment by Miao-Mico** [comment]
> @Miao-Mico The extension is now available on Microsoft Edge also.
> Please check out: https://microsoftedge.microsoft.com/addons/detail/enhanced-github/eibibhailjcnbpjmemmcaakcookdleon

Thanks! In service.
