### ISSUE TITLE
The version 5.0. brought a layout change in some pages of GitHub

### ISSUE THREAD

**Issue by plainheart** [softvar/enhanced-github#68]
Hello there, thank you very much for such a great plugin!

I just find that the new version 5.0.1 seems to have brought a layout change in some pages of GitHub.

Let's look at the commits page https://github.com/ecomfe/zrender/commits/next

It's normal before I enable the plugin.

![image](https://user-images.githubusercontent.com/26999792/95953624-a389d080-0e2c-11eb-89a2-e1870f1912be.png)

After I enabled the plugin. It became untidy and disorganized the original layout.

![image](https://user-images.githubusercontent.com/26999792/95954811-7807e580-0e2e-11eb-854f-95d98c107a59.png)

Please help to check if this is a bug. If confirmed, it would be better to fix ASAP.
Thanks!

**Comment by softvar** [comment]
Thanks for reporting @plainheart . It was a bug.
It has been fixed and released in `v5.0.2`. Please update!

**Comment by plainheart** [comment]
Good job! Thank you for so quick fix.
