### ISSUE TITLE
Symlink is larger than GPLv2

### ISSUE THREAD

**Issue by TheTechRobo** [softvar/enhanced-github#75]
uhh what

![image](https://user-images.githubusercontent.com/52163910/101409438-e9529a80-38ab-11eb-98f5-5f26ce15e013.png)

**Comment by softvar** [comment]
Hey @TheTechRobo,
Can you please provide the link to the repo?

**Comment by TheTechRobo** [comment]
https://github.com/thetechrobo/youtube-dl-gui

**Comment by softvar** [comment]
This is fixed in `v5.0.4`. Please update.
