### ISSUE TITLE
It's all off by 1

### ISSUE THREAD

**Issue by TheTechRobo** [softvar/enhanced-github#79]
SECURITY.md is 756 bytes, NOT palc.py, and the GPL 3.0 is not 847 bytes! And the README.md is 34KB when it should be 2.26!

The .bandit missing the filesize screwed everything up - now each file size is one position lower than it should be.

![image](https://user-images.githubusercontent.com/52163910/103287928-b59df880-49b1-11eb-82dc-ea4b27c09d24.png)

heres' the link: https://github.com/TheTechRobo/python-text-calculator/tree/integrate-mathmod

**Comment by softvar** [comment]
Thanks, @TheTechRobo for reporting this. This is now fixed in v5.0.5. Please update!
