### ISSUE TITLE
How to use GIF in Chrome Extension Icon?

### ISSUE THREAD

**Issue by zydjohnHotmail** [softvar/enhanced-github#88]
Hello:
I have a little experience with chrome extension, I have made 3 extensions now.  They all worked.  But I used png type of icons.
I read some documents, and I found that Chrome support gif type of icons in the extesions.
Now, I have 2 gifs, one is called "stopsoccer.gif", it is actually one stand-still picture of a soccer ball; another one is called "SpinSoccer.gif", it is a soccer ball is spinning, its size is 64px by 64px, it has total of 20 frames.
The following is my manifest.json file:
{
  "name": "Test GIF Icons",
  "version": "1.0",
  "manifest_version": 2,
  "description": "Test GIF Icons",
  "permissions": ["activeTab", "<all_urls>", "storage", "tabs"],
  "background": {
    "scripts": ["background.js"]
  },
  "icons": {
    "64": "icons/SpinSoccer.gif",
    "32": "icons/StopSoccer.gif"
  },
  "browser_action": {
    "default_title": "Test GIF Icon",
    "default_icon": "icons/StopSoccer.gif",
    "default_popup": "popup.html"
  }
}
I want to debug my extension in chrome, I can load my extension without any issue, but I can't see any icon for my extension.
I want to know if there is any requirement for using GIF as icons in chrome extension?
Do I have to use specific size of GIF, I mean the GIF has to be in 32px by 32px or other requirements? 
Anyway, I can't find any example on Github which uses GIF as Chrome extension icons.
Any advice?

**Comment by softvar** [comment]
Not related to this repo.
