### ISSUE TITLE
Repository size not rendered at the expected position

### ISSUE THREAD

**Issue by idadzie** [softvar/enhanced-github#89]
The repository size is not rendered at the expected position. This is an issue for repositories with the autogeneration of a "**table of contents**" option set.

**Comment by Bellisario** [comment]
Here is the problem:
![image](https://user-images.githubusercontent.com/72039923/113411551-5982b000-93b6-11eb-85ac-681dfd66e74d.png)

**Comment by brian6932** [comment]
Yea I have this too, looks weird as hell
![image](https://user-images.githubusercontent.com/18603393/113474340-6d252980-943d-11eb-8ad9-dbe031228cb0.png)

**Comment by softvar** [comment]
Thanks for reporting, @idadzie 
This is fixed in `v5.0.10`.
