### ISSUE TITLE
Repo size is displayed in the wrong position, again

### ISSUE THREAD

**Issue by Jed-Z** [softvar/enhanced-github#93]
For repos with a really simple README.MD file, there would be no `readme-toc` label, causing repo size to be displayed at wrong position.

Here's an example: https://github.com/Jed-Z/algorithm-haystack

**Comment by Jed-Z** [comment]
Seems to have something to do with #89

**Comment by softvar** [comment]
Thanks for reporting, @Jed-Z 
It's fixed in `v5.0.11`
